-- Outbox: make task_id and wakeup_id NULLABLE.
--
-- The 0001 schema enforced both as NOT NULL because every outbox
-- row was assumed to come from an agent's tool call (mailbox_send,
-- tier1_notification — both inside a wakeup). The new
-- `channel_publish` kind breaks that assumption: owner-bound mail
-- sent from the dashboard /send route has no task / wakeup
-- attribution, but still needs to flow through the outbox for
-- kill-safe delivery to external channels.
--
-- Allow NULL on both. The mailbox_send / tier1_notification paths
-- continue to populate them (their enqueue site is inside a
-- wakeup), so the columns remain useful for tracing those flows.
-- `channel_publish` rows get NULL when the source mail wasn't
-- generated by a task (owner→owner or system-injected mail) and
-- inherit the source mail's task_id otherwise.
--
-- SQLite has no ALTER TABLE … DROP NOT NULL, so we use the same
-- rebuild-via-temp-table pattern as 0003.

BEGIN;

CREATE TABLE outbox_v3 (
  id                 INTEGER PRIMARY KEY AUTOINCREMENT,
  task_id            TEXT REFERENCES tasks(id),
  wakeup_id          TEXT REFERENCES wakeups(id),
  kind               TEXT NOT NULL CHECK (kind IN
                       ('mailbox_send','tier1_notification',
                        'channel_publish')),
  payload            TEXT NOT NULL,
  external_id        TEXT NOT NULL,
  created_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  dispatched_at      TEXT,
  dispatch_attempts  INTEGER NOT NULL DEFAULT 0,
  last_error         TEXT,
  UNIQUE (kind, external_id)
);

INSERT INTO outbox_v3 (
  id, task_id, wakeup_id, kind, payload, external_id,
  created_at, dispatched_at, dispatch_attempts, last_error
)
SELECT
  id, task_id, wakeup_id, kind, payload, external_id,
  created_at, dispatched_at, dispatch_attempts, last_error
FROM outbox;

DROP TABLE outbox;
ALTER TABLE outbox_v3 RENAME TO outbox;

COMMIT;
